import Head from 'next/head'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { services } from '../../services'

export async function getStaticProps ({ locale }) {
  const s = await serverSideTranslations(locale, ['common', 'security'])

  return {
    props: {
      ...(s),
      programs: await services.getPrograms(),
      videos: await services.getVideos(),
      headerStyle: 'colored'
      // Will be passed to the page component as props
    }
  }
}

export default function ProgramsPage (props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>

        <pre>
          {JSON.stringify(props.programs, null, 2)}
        </pre>

      </main>

      <footer />
    </>
  )
}
