import Head from 'next/head'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { services } from '../../services'
import Link from 'next/link'

export async function getStaticProps ({ locale }) {
  const s = await serverSideTranslations(locale, ['common', 'security'])

  return {
    props: {
      ...(s),
      programs: await services.getPrograms(),
      videos: await services.getVideos(),
      headerStyle: 'colored'
      // Will be passed to the page component as props
    }
  }
}

export default function ProgramsPage (props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>

        {/* Temporary inline styles and code */}
        <ul style={{ marginBottom: 24, borderBottom: '1px solid black' }}>
          {props.programs.map(program => {
            return (
              <li key={program.slug}>
                <Link key={program.slug} href={`/programs/${program.slug}`}>
                  {program.title}
                </Link>
              </li>
            )
          })}
        </ul>

        <pre>
          {JSON.stringify(props.programs, null, 2)}
        </pre>

      </main>

      <footer />
    </>
  )
}
