import Head from 'next/head'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import { services } from '../../services'
import { Content } from '../../src/views/Blog/SingleBlog/Content'
import { BlogHero } from '../../src/views/Blog/SingleBlog/BlogHero'

export async function getStaticPaths () {
  const slugs = await services.getPostsSlugs()

  const paths = slugs.map(slug => {
    return {
      params: {
        slug
      }
    }
  })

  return {
    paths,
    fallback: false // can also be true or 'blocking'
  }
}

export async function getStaticProps ({ locale, params }) {
  const s = await serverSideTranslations(locale, ['common', 'blog-post'])

  return {
    props: {
      ...(s),
      post: await services.getSinglePost(params.slug),
      videos: await services.getVideos()
      // Will be passed to the page component as props
    }
  }
}

export default function BlogPostPage (props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <BlogHero title={props.post.title} createdAt={props.post.createdAt} timeToRead='10 min' />
        <Content content={props.post.content.html} />
      </main>
    </>
  )
}
