import Head from "next/head";

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import { Home } from "../src/views/Home";
import { services } from "../services";

export async function getStaticProps({ locale }) {
  const s = await serverSideTranslations(locale, ['common', 'home'])

  return {
    props: {
      ...(s),
      blogPosts: await services.getBlogPosts()
      // Will be passed to the page component as props
    },
  };
}

export default function HomePage(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Home blogPosts={props.blogPosts}/>
      </main>
    </>
  );
}
