import Head from 'next/head'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import { services } from '../../services'
import { PdfViewer } from '../../src/components/PdfViewer'

export async function getStaticPaths () {
  const slugs = await services.getAuditSlugs()

  const paths = slugs.map(slug => {
    return {
      params: {
        slug
      }
    }
  })

  return {
    paths,
    fallback: false // can also be true or 'blocking'
  }
}

export async function getStaticProps ({ locale, params }) {
  const s = await serverSideTranslations(locale, ['common', 'security'])

  return {
    props: {
      ...(s),
      audit: await services.getSingleAudit(params.slug),
      videos: await services.getVideos()
      // Will be passed to the page component as props
    }
  }
}

export default function AuditPage (props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <PdfViewer url={`/${props.audit.report}`} />
      </main>
    </>
  )
}
