import Head from "next/head";

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from "react-i18next";
import { getAudits } from "../../src/content";
import styled from "styled-components";
import Link from "next/link";
import { PdfViewer } from "../../src/components/PdfViewer";

export async function getStaticProps({ locale }) {
  const s = await serverSideTranslations(locale, ['security'])

  return {
    props: {
      ...(s),
      audits: await getAudits()
      // Will be passed to the page component as props
    },
  };
}

export default function Home(props) {
  const { t } = useTranslation('security');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {t('h1')}
        </h1>

        {/* <pre>
          {JSON.stringify(props.audits[0].attributes, null, 2)}
        </pre> */}

        <PdfViewer url={`/${props.audits[0].attributes.report}`}/>

        {/* <StyledPdfContainer data={`/${props.audits[0].attributes.report}#view=FitH`} type="application/pdf" width="100%">
          <p>Alternative text - include a link <a href={`/${props.audits[0].attributes.report}`}>to the PDF!</a></p>
        </StyledPdfContainer> */}


      </main>

      <footer>
      </footer>
    </>
  );
}

/* 
const StyledPdfContainer = styled.object`
  height: 90vh;
  min-height: 600px
` */