import Head from 'next/head'
import { mockData } from '../../../services/_mock_'
import { BlogPost } from '../../../src/views/Blog/SingleBlog'

export default function SingleBlog () {
  // const router = useRouter()

  const postId = mockData.articleList.docs[0].id

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <BlogPost postId={postId} />
      </main>
    </>
  )
}
